### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by waifwu**
more cgs

### CODE REVIEW

**Comment by waifwu** [comment]
@rschlaikjer Can you check if file names are correct? I don't have the allpac

**Comment by rschlaikjer** [comment]
hmm, 0338 looks like a bike shed to me

**Comment by waifwu** [comment]
probably wrong then, i took them from the e-hentai website that ivan shared

**Comment by rschlaikjer** [comment]
weird, the others were correct

**Comment by AtaIanta** [comment]
The pictures on e-hentai are only reference, do not use them cause some of them have lower quality. 

There are 4 pictures of security fence:
img0454.jpg
img0454_01_01.jpg
img0454_04_04.jpg
img0454_05_05.jpg

**Comment by AtaIanta** [comment]
Upon further investigation it was also discovered that warning signs are available as img3329.jpg, img3321.jpg and img3320.jpg. I assume this are their gallery version.

**Pull request merged**
