### PR TITLE
Faster / filename-safe mrg patching

### PR DESCRIPTION
**Pull request by rschlaikjer**
Added some tools to [this project](https://github.com/rschlaikjer/mangetsu), specifically `mrg_extract`/`mrg_pack` and `nxx_decompress`/`nxgx_compress` to hopefully allow some finer manipulation of the game data files. They are also a lot faster than BMS - doing a full repack with the new script is ~8 seconds, most of which is converting PNGs to textures. If the PNGs are already converted, doing a full extract / compress cycle is only ~3 seconds.

HOWEVER, I am currently investigating the meaning behind the final u16 field in the HED entry struct - if I ignore it and leave it zeroes, the game fails to boot, but if I repack the data and copy in the old values it loads fine. It doesn't seem to be a size. Tomorrow will check if it is the number of sub-files in the entry? Until this is resolved, please do not merge.

### CODE REVIEW

**Comment by harphield** [comment]
This is great! Making the slowest parts (PNG -> DDS conversion and MRG repacking) faster will help a lot.

How would your tool handle multiple files with same name in allpac.nam? allpac.mrg has each texture in thumbnail and full size, but in allpac.nam they are named the same, the only difference is position in sequence. Quickbms can't handle that. Fortunately the original sizes are first, so it just skips the thumbnails and it works OK, but still.

**Comment by rschlaikjer** [comment]
When you're packing a mrg, you can supply a list of file names to use with the `--names` argument, and it will use those names in-order for the input files to pack, that way you can have as many files as you need with the same name but different contents

**Comment by harphield** [comment]
> When you're packing a mrg, you can supply a list of file names to use with the `--names` argument, and it will use those names in-order for the input files to pack, that way you can have as many files as you need with the same name but different contents

Hmm but that means you always have to repack everything that was unpacked, correct? Quickbms has a nice feature that you can only put some files into a folder and it will only reinsert those files. This is nice for large files (like the 15GB allpac.mrg).

**Comment by rschlaikjer** [comment]
Yeah, true. I can add an option to replace by index or something so that
you don't generate as many temporary files.

**Comment by rschlaikjer** [comment]
The API for dealing with the files is pretty simple, so wouldn't take much work
https://github.com/rschlaikjer/mangetsu/blob/master/src/tools/mrg_pack.cpp

**Pull request merged**
